# Generated by Django 3.2.8 on 2021-10-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('step_no', models.IntegerField()),
                ('step', models.TextField()),
                ('time', models.CharField(max_length=8)),
            ],
        ),
    ]
