# Generated by Django 3.2.8 on 2021-10-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe',
            new_name='recipe_id',
        ),
    ]
